### ISSUE TITLE
[BUG]  Issue with elpa Folder Deletion

### ISSUE THREAD

**Issue by ehsanirani** [abougouffa/minemacs#127]
**Describe the bug**
Hello,

I've encountered an issue after pulling the latest commits. Each time I run Emacs with this version, the `elpa` folder is unexpectedly deleted. It leads to reinstalling all the packages that I added to my config every time I run emacs. This behavior was not observed in the previous version 3.6.1. Could there be a change in the latest commits that might be causing this issue?

By the way, I wanted to express my appreciation for your work on minemacs. It's been an excellent tool. Great config!

Thanks!

**Emacs version**
GNU Emacs 30.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-03-20

**To Reproduce**
1. Create a `elpa` folder in `.emacs.d`
2. Check it is deleted after a while

**Expected behavior**
elpa folder should stays in the .emacs.d folder

**Comment by abougouffa** [comment]
Hello @ehsanirani 

Thank you for the feedback. Yep, I intentionally added a function which I call in `init.el` to cleanup the `.emacs.d` directory (removes `elpa` among other directories).

MinEmacs uses `straight.el` to install packages, the `elpa` directory is where the builtin `package` installs packages. It is not recommended to use two packages managers in the same configuration.

I've taken a look into your `dotfiles` repo, you need to use `:straight t` instead of `:ensure t` in your `use-package` blocks. Like in here:

https://github.com/ehsanirani/dotfiles/blob/65a666b97de9b460087a91e6caa3ca93dc4c48b8/.minemacs.d/ehsan-modules/ee-org.el#L14
