### ISSUE TITLE
[BUG] Asking for "Font installation directory" each startup

### ISSUE THREAD

**Issue by orazdow** [abougouffa/minemacs#154]
On each startup nothing loads except the minibuffer displaying the message: "Font installation directory: ~/" 
I've tried inputting various paths, each time it will say "Sucessfuly downloaded Nerd icons" and download NFM.ttf to that path.
After that, minemacs starts but the same behavior is repeated each time I start emacs.

Added context: I am loading minemacs by adding this to the default init.el:

(add-to-list 'load-path "~/.config/minemacs")

(load-file "c:/USers/ollie/.config/minemacs/init.el")

Windows 11, emacs version 29.2

**Comment by abougouffa** [comment]
Hi @orazdow ,

Thank you for the reporting this.

MinEmacs is not officially supported on Windows (I'm trying to have a **runnable** config on Windows but, I didn't properly test it since I don't use Windows). It should work on Windows with the defaults, there are folks out there using it on Windows, but I can't guarantee anything, especially when tweaking the configuration options like changing the installation directory.

Do you get the same behavior if you use the default installation directory (`~/.emacs.d/`) ?

**Comment by orazdow** [comment]
I think it is the fact that I redirected the directory, combined with how windows treats the home directory. I'm using my own config for now so I didn't try redoing it in the default directory, but I think that was almost definitely the problem, so I think you can close this as a 'frivolous issue' heh.
