### ISSUE TITLE
[BUG] MIemacs start interface shortcut keys are invalid

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#170]
I upgraded to tag 6.8.2 and started minemacs
press p   project
press a   org
not work

**Comment by abougouffa** [comment]
Hi @donneyluck 

Thank you for the feedback.

I replaced `dashboard` with `enlight` because it is a lot lighter and faster. `dashboard` was loading a lot of packages, hence making Emacs slow at startup.

TBH, I'm not using the dashboard in my config, I prefer using the normal keybinding instead of `enlight`'s one (`SPC p p` and so on). And for the moment, there is no support for `enlight` in `evil-collection` (I think I will wait until they do it instead of adding some glue to make it work).

**Comment by ichernyshovvv** [comment]
I have no experience in writing evil extensions. If you know how to do that, feel free to send PR to evil-collection
