### ISSUE TITLE
is there language module to custom

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#24]
hi. i want to add some language-mode.  like  cc-mode  csharp-mode
which file should i  add

**Comment by abougouffa** [comment]
The custom configuration files are located in `$MINEMACSDIR` or defaults to `~/.minemacs.d/` if the environment variable is not defined (you can evaluate `minemacs-config-dir` to see yours).

For custom modules, you can add them either to `~/.minemacs.d/config.el` or `~/.minemacs.d/modules.el`. I suggest adding them to `~/.minemacs.d/config.el` [which gets loaded at the end of `init.el`](https://github.com/abougouffa/minemacs/blob/c48cceca4ff52df70c472f135f6a5eed178ef735/init.el#L283-L286) and after loading all modules.

You can also add them to `~/.minemacs.d/modules.el` which is evaluated [early in init stage](https://github.com/abougouffa/minemacs/blob/c48cceca4ff52df70c472f135f6a5eed178ef735/init.el#L231-L234) (before loading MinEmacs modules), hence, it can be useful for packages that should be loaded too early. The `config.el`.

For the syntax, I recommend using `use-package` and `straight` as MinEmacs uses these two to install new packages. Please note that in `me-bootstrap`, [I set `use-package` to always defer loading packages](https://github.com/abougouffa/minemacs/blob/c48cceca4ff52df70c472f135f6a5eed178ef735/core/me-bootstrap.el#L42), unless `:demand t` is provided.

For example, to add `csharp-mode` support, you can add this to your `config.el`:

```elisp
(use-package csharp-mode
  :straight (:type built-in)
  :mode "\\.cs\\'"
  :custom 
  (csharp-ts-mode-indent-offset 2)) ; customize variables
```

Or, since `csharp-mode` and `cc-mode` are built-in packages, you can use customize them in `with-eval-after-load` blocks in `config.el`:

```elisp
(with-eval-after-load 'csharp-mode
  (setq csharp-ts-mode-indent-offset 2) ; customize variables
  
  ;; Add a keybinding for `some-command` as "SPC m x"
  (+map-local :keymaps 'csharp-mode-map 
    "x" #'some-command))
```

Hope this answers your question!

**Comment by abougouffa** [comment]
@donneyluck Please close the issue if this answers your question.
