### ISSUE TITLE
Iosevka Fixed Curly Slab  not support ligature

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#29]
hi @abougouffa   
after my test   
font you recommend Iosevka Fixed Curly Slab  not support ligature
so i try JetBrains Mono  
work well 
![image](https://user-images.githubusercontent.com/122257591/225197997-864b575b-babf-4972-815f-56b9bcbb3101.png)

**Comment by abougouffa** [comment]
Yep I know, I prefer Iosevka fonts because the are compact and can display longer lines. There is some of the Iosevka fonts (these patched in NerdFonts) that supports ligatures, they don't contain the word "Fixed" in the font name. However, I didn't recommend them because they aren't really fixed width, they can mess the layout of `which-key`.
