### ISSUE TITLE
How to Implement a Web Search Engine

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#36]
hi,@abougouffa 
i want Implement a Search Engine like doom emacs press SPC s o (search online)
but i don`t know how to do this （I have not written a elisp package）
can you implement an example for me  in minemacs 
thks for your time
<img width="601" alt="image" src="https://user-images.githubusercontent.com/122257591/226182194-954b5d1f-548c-4654-b833-e5dcf07d3379.png">

**Comment by abougouffa** [comment]
Hello @donneyluck,

I don't know what package Doom Emacs uses for this, but there is a built-in package named `webjump` which can be easily customized to include any search engine (via `webjump-sites`).

**Comment by donneyluck** [comment]
hi @abougouffa 
i have test it (+webjump)
there is some problem
when +region-org-thing-at-point is null     
got error
`bounds-of-thing-at-point: Wrong type argument: characterp, nil`

**Comment by abougouffa** [comment]
Thank you for the feedback, I've tried the `+region-org-thing-at-point` in the described case, but I can't reproduce the error.

The current implementation of `+webjump` is a POC to *how to implement a command to search online*, you can modify it or make your own copy to implement other behaviors in `config.el`.

Please note that (as I've explained in the [README](https://github.com/abougouffa/minemacs#why)) MinEmacs is **just a personal Emacs configuration**, and it is not intended to be a Doom Emacs or Spacemacs competitor. I've tried though to make it extensible (via `~/.minemacs.d/{early-config,init-tweaks,config,modules}.el`) so users can benefit from the base config and fit it to their workflows.

Emacs is a great tool, but configuring it can quickly become a rabbit hole, taking more and more time to configure the tool rather than doing the real work. I've started MinEmacs essentially because of this, I was facing a bunch of problems each time I upgrade Doom Emacs, which makes me lost valuable work time trying to fix these issues.
