### ISSUE TITLE
Support on apple M1/M2

### ISSUE THREAD

**Issue by mandarvaze** [abougouffa/minemacs#5]
I'm getting error related to `parinfer-rust` saying it requires aarm64, but got x86_64 (or something to that effect)

Could be due to [this](https://github.com/abougouffa/minemacs/blob/11cb5ae2297e86248d570eef65b325b7e1ae4f1e/modules/me-lisp.el#L13)

**Comment by abougouffa** [comment]
Strange! 

You can try to enter your `~/.emacs.d/`, cleanup installed packages and launch Emacs again.

Run:

```shell
cd ~/.emacs.d
make clean
emacs
```

Or you can try to run Emacs with `--debug-init` to see what is causing the problem.

**Comment by abougouffa** [comment]
Hello @mandarvaze 

Yep, I'm aware of this problem (the condition you've pointed is in fact part of a workaround to avoid this issue).

This is caused by `parinfer-rust-mode`, which do not provide precompiled libraries for architectures other than x86_64. 

In your case, you can compile `parinfer-rust` from source ([see build instruction form here](https://github.com/justinbarclay/parinfer-rust-mode#option-2-building-library-from-sources)), then add this to your config.el.

```elisp
(setq parinfer-rust-library "/path/to/your/parinfer-rust-library.so")
```

**Comment by mandarvaze** [comment]
I bypassed the problem by commenting `me-lisp` in my modules.el :)
I'm not sure I need it 🤷‍♂️
