### ISSUE TITLE
about org-mode org-src

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#55]
@abougouffa hi
In the past few days, when I use org-mode to insert code blocks, there will be smart prompts

But after the latest update, after I press <, it won't help me to complete the code type, I don't know what happened

not the package yasnippet 

just press <   then can choose src code type

**Comment by donneyluck** [comment]
![image](https://user-images.githubusercontent.com/122257591/235096794-71d3e3d2-3cf5-4fb1-b6d4-21a77643760a.png)

maybe this package  
in org-mode  then evil-insert  <           nothing happy 
It was hinted before

**Comment by donneyluck** [comment]
https://github.com/abougouffa/minemacs/commit/9360b69ca944b5b044d7032ca2953388bb7fc55c

this commit  (corfu-exclude-modes '(org-mode markdown-mode))  will cause this problem

**Comment by abougouffa** [comment]
Hello @donneyluck ,

Thank you for bringing this to my attention.

It is the change you mentioned which triggers this behavior. I disabled `corfu` in `org-mode` because I was getting annoying word completion based on `dabbrev` (or something like it).

It is indeed useful to enable `corfu` for better completion of snippets.

I will patch this soon, thanks again!

**Comment by abougouffa** [comment]
Fixed in be458ac11783280643bcf75c0332231bb7fb63dc.
