### ISSUE TITLE
about  me-multi-cursors

### ISSUE THREAD

**Issue by donneyluck** [abougouffa/minemacs#57]
hello @abougouffa 
This file contains some multi-cursor packages
After my test   evil-multiedit is my favorite
but there is a small problem
When multiple regions are selected   ' kj '  Cannot deselect region
evil-escape work well   but can`t do   evil-multiedit-abort
I don't know how to fix it please help me

**Comment by abougouffa** [comment]
Yes, I'm aware of this issue. I've tried before to fix it, but I didn't manage to. 

The `evil-escape` package supports `evil-multiedit` [as you can see in it source code](https://github.com/syl20bnr/evil-escape/blob/f4e9116bfbaac8c9d210c17ad488e0982291245f/evil-escape.el#L175-L176). 

However, it seems that `evil-multiedit` do not manage the `evil-state` correctly. For example, when pressing `g z e m` to mark all matches (`evil-multiedit-match-all`), when you position the cursor on one of the occurrences and `M-:` then evaluate `evil-state`, it will show `normal` instead of `multiedit`. So, with this behavior of `evil-multiedit`, the [`evil-escape-func` won't work as predicted](https://github.com/syl20bnr/evil-escape/blob/f4e9116bfbaac8c9d210c17ad488e0982291245f/evil-escape.el#L175-L176).

**Comment by donneyluck** [comment]
I tried to fix him via chatgpt but failed
